# Path to your oh-my-zsh installation.
export ZSH="/home/${USER}/.oh-my-zsh"

# Themes
ZSH_THEME_RANDOM_CANDIDATES=("simple" "nicoulaj" "zhann")
ZSH_THEME=random

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Plugins
plugins=(git, vim-mode)

source $ZSH/oh-my-zsh.sh

# Personal aliases
alias zconf="nvim ~/.zshrc"
alias ozconf="mate ~/.oh-my-zsh"

# vim-mode 
bindkey -v
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward
function zle-line-init zle-keymap-select {
    RPS1="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
    RPS2=$RPS1
    zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select
export KEYTIMEOUT=1
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
